#!/bin/bash
set -e

[ -e /tmp/computed_vars.source.bash ] && source /tmp/computed_vars.source.bash

CELERYD_OPTIONS='--loglevel=DEBUG --time-limit=900 --maxtasksperchild=5'

cd /srv/src/kobocat

/sbin/setuser wsgi python manage.py celeryd $CELERYD_OPTIONS
