# Generated by Django 2.2.14 on 2021-03-15 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0016_remove_conflicting_view_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xform',
            unique_together={('user', 'id_string')},
        ),
        migrations.RemoveField(
            model_name='xform',
            name='allows_sms',
        ),
        migrations.RemoveField(
            model_name='xform',
            name='sms_id_string',
        ),
    ]
