# Generated by Django 2.2.14 on 2021-05-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0017_remove_xform_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeAuthRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ttl', models.IntegerField(default=60)),
                ('method', models.CharField(max_length=6)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticated_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('token', 'used')},
            },
        ),
    ]
