# Generated by Django 2.2.14 on 2022-02-17 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0020_submission_counter_timestamp_as_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
