# Generated by Django 2.2.14 on 2022-04-05 17:08

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def merge_and_remove_duplicates(apps, scheme_editor):
    """
    Remove all duplicate submission counters. 
    """
    SubmissionCounter = apps.get_model('logger', 'SubmissionCounter')
    submission_counters = SubmissionCounter.objects.values(
        'timestamp', 'user'
    ).annotate(
        Count('pk')
    ).filter(pk__count__gt=1)

    to_delete = []

    for sc in submission_counters:
        to_delete.extend(SubmissionCounter.objects.filter(
            timestamp=sc['timestamp'], user=sc['user'],
        ).values_list('pk', flat=True)[1:])
        print('.', end='', flush=True)

    SubmissionCounter.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0022_misc_model_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissioncounter',
            unique_together={('user', 'timestamp')},
        ),
    ]
