# Generated by Django 3.2.15 on 2023-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0032_alter_daily_submission_counter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
