# Generated by Django 3.2.15 on 2023-10-05 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0032_alter_daily_submission_counter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
