---
aws_region: us-east-1
environmentVariables:
  PUBLIC_REQUEST_SCHEME: http
  PUBLIC_DOMAIN_NAME: dev.veritree.com
  INTERNAL_DOMAIN_NAME: veritree
  KOBOFORM_PUBLIC_SUBDOMAIN: kf
  KOBOCAT_PUBLIC_SUBDOMAIN: kc
  ENKETO_EXPRESS_PUBLIC_SUBDOMAIN: ee
  KOBO_SUPPORT_EMAIL: support@dev.veritree.com

  MONGO_INITDB_DATABASE: formhub
  #MONGO_BACKUP_SCHEDULE: 0 1 * * 0
  POSTGRES_PORT: 5432
  POSTGRES_HOST: dev-kobocat.cluster-cxqhyxx46hk7.us-east-1.rds.amazonaws.com
  KC_POSTGRES_DB: kobocat
  KPI_POSTGRES_DB: koboform
  #POSTGRES_BACKUP_SCHEDULE: 0 2 * * 0
  #USE_WAL_E: 1
  #REDIS_BACKUP_SCHEDULE: 0 3 * * 0

  KOBOCAT_DEFAULT_FILE_STORAGE: storages.backends.s3boto.S3BotoStorage
  KOBOCAT_AWS_STORAGE_BUCKET_NAME: kc.dev.veritree.com
  KPI_DEFAULT_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
  KPI_AWS_STORAGE_BUCKET_NAME: kf.dev.veritree.com
  BACKUP_AWS_STORAGE_BUCKET_NAME: backup.dev.veritree.com
  # AWS_BACKUP_BUCKET_DELETION_RULE_ENABLED: False
  # AWS_BACKUP_YEARLY_RETENTION: 2
  # AWS_BACKUP_MONTHLY_RETENTION: 12
  # AWS_BACKUP_WEEKLY_RETENTION: 4
  # AWS_BACKUP_DAILY_RETENTION: 30
  # AWS_BACKUP_UPLOAD_CHUNK_SIZE: 15

  GOOGLE_ANALYTICS_TOKEN: ""
  KOBOCAT_RAVEN_DSN: ""
  KPI_RAVEN_DSN: ""
  KPI_RAVEN_JS_DSN: ""

  KPI_WEB_SERVER: uWSGI
  KC_WEB_SERVER: uWSGI
  KOBOCAT_STATIC_FILES_SERVER: Nginx
  KPI_STATIC_FILES_SERVER: Nginx

  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: ""
  EMAIL_PORT: 25
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_USE_TLS: False
  DEFAULT_FROM_EMAIL: support@dev.veritree.com

  ENKETO_PROTOCOL: http
  KPI_PORT: 8003
  KC_UWSGI_MAX_REQUESTS: 512
  KC_UWSGI_WORKERS_COUNT: 2
  KC_UWSGI_CHEAPER_RSS_LIMIT_SOFT: 134217728
  KC_UWSGI_CHEAPER_WORKERS_COUNT: 1
  NGINX_PUBLIC_PORT: 80
  KC_UWSGI_HARAKIRI: 120
  KC_UWSGI_WORKER_RELOAD_MERCY: 120
  DJANGO_SETTINGS_MODULE: onadata.settings.prod

  KOBOCAT_DJANGO_DEBUG: True
  TEMPLATE_DEBUG: True
  #USE_X_FORWARDED_HOST: True
  # DJANGO_SETTINGS_MODULE: onadata.settings.kc_environ
  ENKETO_VERSION: Express
  KOBOCAT_CELERY_LOG_FILE: /srv/logs/celery.log
  #KOBOCAT_MEDIA_BACKUP_SCHEDULE: 0 0 * * 0
  KOBOCAT_MONGO_HOST: kb-dev-formhub.cluster-cxqhyxx46hk7.us-east-1.docdb.amazonaws.com
  KOBOCAT_MONGO_PORT: 27017
  KOBOCAT_MONGO_NAME: formhub
  KOBOCAT_MONGO_USER: kobo

  KPI_DJANGO_DEBUG: True
  # TEMPLATE_DEBUG: False
  #USE_X_FORWARDED_HOST: True
  # ENKETO_VERSION: Express
  KPI_PREFIX: /
  KPI_MONGO_HOST: kb-dev-formhub.cluster-cxqhyxx46hk7.us-east-1.docdb.amazonaws.com
  KPI_MONGO_PORT: 27017
  KPI_MONGO_NAME: formhub
  KPI_MONGO_USER: kobo
  DJANGO_LANGUAGE_CODES: en ar es fr hi ku pl pt zh-hans

  SYNC_KOBOCAT_XFORMS: False # Should be True on at least one frontend environment
  KPI_UWSGI_MAX_REQUESTS: 512
  KPI_UWSGI_WORKERS_COUNT: 2
  KPI_UWSGI_CHEAPER_RSS_LIMIT_SOFT: 134217728
  KPI_UWSGI_CHEAPER_WORKERS_COUNT: 1
  # NGINX_PUBLIC_PORT: 80
  KPI_UWSGI_HARAKIRI: 120
  KPI_UWSGI_WORKER_RELOAD_MERCY: 120
  # SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO, https
  # FRONTEND_DEV_MODE: host


  # NGINX_PUBLIC_PORT: 80
  UWSGI_PASS_TIMEOUT: 130
  TEMPLATED_VAR_REFS: $${PUBLIC_REQUEST_SCHEME} $${INTERNAL_DOMAIN_NAME} $${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}

  ENKETO_BUILD_IE11: true

  VERITREE_OAUTH_CLIENT_ID: 5 #review
  VERITREE_HOOKS_EMAIL: monitoring.hooks@veritree.com #review

secrets:
  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_SUPERUSER_USERNAME"
    property: "KOBO_SUPERUSER_USERNAME"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_SUPERUSER_PASSWORD"
    property: "KOBO_SUPERUSER_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "ENKETO_API_KEY"
    property: "ENKETO_API_KEY"

  - key: "/kubernetes/dev/kobo/app"
    name: "ENKETO_API_TOKEN"
    property: "ENKETO_API_TOKEN"

  - key: "/kubernetes/dev/kobo/app"
    name: "ENKETO_ENCRYPTION_KEY"
    property: "ENKETO_ENCRYPTION_KEY"

  - key: "/kubernetes/dev/kobo/app"
    name: "DJANGO_SECRET_KEY"
    property: "DJANGO_SECRET_KEY"

  - key: "/kubernetes/dev/kobo/app"
    name: "MONGO_INITDB_ROOT_USERNAME"
    property: "MONGO_INITDB_ROOT_USERNAME"

  - key: "/kubernetes/dev/kobo/app"
    name: "MONGO_INITDB_ROOT_PASSWORD"
    property: "MONGO_INITDB_ROOT_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "POSTGRES_USER"
    property: "POSTGRES_USER"

  - key: "/kubernetes/dev/kobo/app"
    name: "POSTGRES_PASSWORD"
    property: "POSTGRES_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "REDIS_PASSWORD"
    property: "REDIS_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_BROKER_URL"
    property: "KPI_BROKER_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_MONGO_PASS"
    property: "KPI_MONGO_PASS"

  - key: "/kubernetes/dev/kobo/app"
    name: "VERITREE_OAUTH_CLIENT_SECRET"
    property: "VERITREE_OAUTH_CLIENT_SECRET"

  - key: "/kubernetes/dev/kobo/app"
    name: "VERITREE_HOOKS_EMAIL_PASSWORD"
    property: "VERITREE_HOOKS_EMAIL_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KC_DATABASE_URL"
    property: "KC_DATABASE_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_DATABASE_URL"
    property: "KPI_DATABASE_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "REDIS_LOCK_URL"
    property: "REDIS_LOCK_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_POSTGRES_REPLICATION_USER"
    property: "KOBO_POSTGRES_REPLICATION_USER"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_POSTGRES_REPLICATION_PASSWORD"
    property: "KOBO_POSTGRES_REPLICATION_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_MONGO_PASSWORD"
    property: "KOBO_MONGO_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBOCAT_BROKER_URL"
    property: "KOBOCAT_BROKER_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBOCAT_MONGO_PASS"
    property: "KOBOCAT_MONGO_PASS"

  - key: "/kubernetes/dev/kobo/app"
    name: "REDIS_SESSION_URL"
    property: "REDIS_SESSION_URL"

clusterIssuer: letsencrypt-dev

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::311934536039:role/kobo-dev"

volume:
  media:
    size: 50Gi
    efsId: fs-06b89915e1acd1fcf::fsap-084572719d03d18d8
  static:
    size: 1Gi
    efsId: fs-06b89915e1acd1fcf::fsap-084572719d03d18d8

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    alb.ingress.kubernetes.io/tags: EKS=True
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: "veritree-kb-dev"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  hosts:
    - host: kc.dev.veritree.com
      paths:
        - /*
  tls:
    - hosts:
        - kc.dev.veritree.com
      secretName: veritree-kobo-dev-cert
