kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kc-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kc-pv
spec:
  capacity:
    storage: {{ .Values.volume.media.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kc-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volume.media.efsId }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kc-sc
  resources:
    requests:
      storage: {{ .Values.volume.media.size }}
---
