# Generated by Django 3.2 on 2022-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_update_meta_data_export_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedinstance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
